#!/usr/bin/env bash
COMPOSE="docker-compose -f demo-base.yml \
    \
    -f event-bus/docker/base.yml \
    -f event-bus/docker/event-bus.yml \
    \
    -f bfaf/docker-compose.yml \
    -f user-interface/docker-compose.yml \
    \
    -f jackie/docker-compose.yml \
    \
    -f demo-overrides.yml"

RED='\x1B[0;31m'
GREEN='\x1B[0;32m'
AMBER='\x1B[0;33m'
BLUE='\x1B[0;34m'
NC='\x1B[0m' # No Color

case $1 in
  "setup")
      echo -e "${AMBER}Pulling required docker images...$NC"
      $COMPOSE pull

      echo -e "${AMBER}Building required docker images... this may take some time!$NC"
      $COMPOSE build
      ;;
  "run")
      echo -e "${GREEN}Starting the Admin UI...$NC"
      $COMPOSE up -d admin_ui
      
      echo -e "${GREEN}Starting the bare dependencies... (kafka, couchbase, redis)...$NC"
      $COMPOSE up -d \
          zookeeper kafka \
          couchbase.db \
          redis

      secs=$((30))
      while [ $secs -gt 0 ]; do
         echo -e "Waiting for ${BLUE}dependencies$NC to spool up sufficiently... $GREEN$secs$NC seconds remaining"
         sleep 1
         : $((secs--))
      done

      echo -e
      echo -e
      echo -e "${GREEN}Starting the event bus...$NC"
      $COMPOSE up -d eventbus

      secs=$((15))
      while [ $secs -gt 0 ]; do
         echo -e "Waiting for ${BLUE}event bus$NC to spool up sufficiently... $GREEN$secs$NC seconds remaining"
         sleep 1
         : $((secs--))
      done
      
      
      echo -e
      echo -e
      echo -e "${GREEN}Starting microservices...$NC"
      $COMPOSE up -d accountsservice transactionservice userservice
      
      
      secs=$((10))
      while [ $secs -gt 0 ]; do
         echo -e "Waiting for ${BLUE}microservices$NC to spool up sufficiently... $GREEN$secs$NC seconds remaining"
         sleep 1
         : $((secs--))
      done

      echo -e
      echo -e
      echo -e "${GREEN}Starting everything else... bfaf/jackie/etc$NC"
      $COMPOSE up -d

      secs=$((10))
      while [ $secs -gt 0 ]; do
         echo -e "Waiting for ${BLUE}everything else$NC to spool up sufficiently... $GREEN$secs$NC seconds remaining"
         sleep 1
         : $((secs--))
      done
      echo -e
      echo -e
      echo -e "==================="
      echo -e
      echo -e "${GREEN}Services state:$NC"
      echo -e
      $COMPOSE ps
      echo -e
      echo -e "${AMBER}Please investigate if there are any services not 'Up' in the above list!$NC"
      echo -e
      echo -e
      ;;
  "stop")
      echo -e "${AMBER}Stopping....$NC"
      $COMPOSE down
      echo -e "${GREEN}Stopped....$NC"
      ;;
  "logs")
      clear
      echo -e "${GREEN}Starting stream of logs....$NC"
      sleep 1

      $COMPOSE logs -f
      ;;
  "compose")
      shift
      eval "$COMPOSE $@"
      ;;
  "restart_clients")
      echo -e "${AMBER}Restarting Accounts Service....$NC"
      $COMPOSE restart accountsservice

      echo -e "${AMBER}Restarting Transaction Service....$NC"
      $COMPOSE restart transactionservice

      echo -e "${AMBER}Restarting User Service....$NC"
      $COMPOSE restart userservice
      ;;
  "restart_proxies")
      echo -e "${AMBER}Restarting Accounts Service proxy....$NC"
      $COMPOSE restart accounts_proxy

      echo -e "${AMBER}Restarting Transaction Service proxy....$NC"
      $COMPOSE restart transaction_proxy

      echo -e "${AMBER}Restarting User Service proxy....$NC"
      $COMPOSE restart user_proxy
      ;;
  "restart_bus")
      echo -e "${RED}Restarting event bus...$NC"
      $COMPOSE restart eventbus
      ;;
  *)
      echo -e "${RED}================="
      echo -e
      echo -e "${GREEN}Welcome to SED Event Bus Demo!$NC"
      echo -e
      echo -e "Commands:"
      echo -e
      echo -e "\t${GREEN} run$NC              \t Put all necessary docker containers up in a managed, error-free way."
      echo -e "\t${GREEN} stop$NC             \t Tear everything down."
      echo -e "\t${GREEN} logs$NC             \t Get logs from docker-compose about everything that's running."
      echo -e "\t${GREEN} compose$NC          \t Run docker compose commands easily without having to copy/paste the -f flags"
      echo -e "\t${GREEN} restart_clients$NC  \t Use this to kick the microservices a bit if they lost connection to the bus."
      echo -e "\t${GREEN} restart_bus$NC      \t Use this to kick the bus."
      echo -e
      echo -e
      ;;
esac

# vim: ft=sh
