version: '3'

services:
  accountsservice:
    build: ./accounts-service
    ports:
      - 5003:5003
  transactionservice:
    build: ./transaction-service
    ports:
      - 5004:5004
  userservice:
    build: ./user-service
    ports:
      - 5005:5005
