version: '3'

services:
  couchbase.db:
    build: ./event-bus/docker/couchbase
  eventbus:
    build: ./event-bus
    ports:
      - 8081:8081
    command: busd -l debug server --bind eventbus:8081 --broker kafka:9092
  bfaf:
    build: ./bfaf
  frontend:
    build: ./user-interface
