version: '3'

services:
  accountsservice:
    build:
      context: ./event-bus
      dockerfile: Dockerfile.service
    command: serviced services/account.lua -b 0.0.0.0:5003 -s ws://eventbus:8081 -r redis://redis:6379/0
    ports:
      - 5003:5003
    depends_on:
      - eventbus
  transactionservice:
    build:
      context: ./event-bus
      dockerfile: Dockerfile.service
    command: serviced services/transaction.lua -b 0.0.0.0:5003 -s ws://eventbus:8081 -r redis://redis:6379/1
    ports:
      - 5004:5004
    depends_on:
      - eventbus
  userservice:
    build:
      context: ./event-bus
      dockerfile: Dockerfile.service
    command: serviced services/user.lua -b 0.0.0.0:5003 -s ws://eventbus:8081 -r redis://redis:6379/2
    ports:
      - 5005:5005
    depends_on:
      - eventbus
